# Generated by Django 5.2.1 on 2025-06-05 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('list_of_tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timehack_app.listoftasks', verbose_name='List')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timehack_app.task', verbose_name='Task')),
            ],
        ),
    ]
